POST http://localhost:3000/api/url/shorten 
content-type: application/json

{
  "longUrl": "https://www.yakaboo.ua/ua/knigi.html?dir=desc&gclid=CjwKCAiAnO2MBhApEiwA8q0HYaZupb5xBsv7dVOoySMeUqTnu0gKkPsKtpcCj_O18UlPF2l-HyGHfhoCMN8QAvD_BwE&order=popularity"
}